services:
  - type: web
    name: chess-analytics-hub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app app run --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: CHESS_URL
        value: https://suphawitka69-sketch.github.io/Chess-with-Ai-Recognization/